zaakafhandelcomponent-1224 heropende zaken op afgehandelde werkvoorraad
NL-AMS-LOCGOV/zaakafhandelcomponent pull request #1353
Opened 2022-07-19 11:10 UTC by jeroen-dekker

Alleen zaken die in SOLR geindexeerd zijn met StatusEindstatus worden geretourneerd bij het ophalen van afgesloten zaken.

2022-07-19 13:52 UTC, andyverberne requested changes

2022-07-21 14:10 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekObject.java
> +    public static final String
Was foutieve duplicate. Aangepast en gefixt.

2022-07-21 14:10 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/zoeken/converter/RESTZoekParametersConverter.java
> +            zoekParameters.addFilterQuery(ZaakZoekObject.EINDSTATUS_FIELD, BooleanUtils.TRUE);
Overbodig geworden regel is verwijderd.

2022-07-21 14:11 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/zoeken/converter/RESTZaakZoekObjectConverter.java
> +        restZoekItem.statusEindstatus = zoekItem.isStatusEindstatus();
Beide objecten (front- en back-end) opgeschoond. De objecten komen nu weer overeen qua naamgeving en attributen.

2022-07-24 07:11 UTC, merged