zaakafhandelcomponent-1584 Voeg samenvatting toe aan zip-download
NL-AMS-LOCGOV/zaakafhandelcomponent pull request #1632
Opened 2022-09-23 13:17 UTC by jeroen-dekker

2022-09-26 09:30 UTC, marcoatos requested changes

2022-09-26 09:30 UTC, marcoatos commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +            final Map<String, List<String>> zaakRichtingen = samenvatting.get(zaak);
Waarom maak hier eerst een nieuwe object van voordat je gaat loopen, dat doe je bij de andere 2 loops niet.

2022-09-26 13:24 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +    private static final String ZAAK_ONTKOPPELD = "ontkoppeld";
Opgelost in opvolgende commit

2022-09-26 13:24 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +    public StreamingOutput getZipFileFor(final List<UUID> uuids) {
Opgelost in opvolgende commit

2022-09-26 13:25 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +            try (ZipOutputStream zipOutputStream = new ZipOutputStream(new BufferedOutputStream(outputStream))) {
Die final fields moet ik beter op letten. Opgelost in opvolgende commit.

2022-09-26 13:25 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +                Map<String, Map<String, List<String>>> samenvatting = new HashMap<>();
Opgelost in opvolgende commit

2022-09-26 13:25 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +                    String pad = addInformatieObjectToZip(uuid, zipOutputStream);
Opgelost in opvolgende commit

2022-09-26 13:26 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +        final String path = getInformatieObjectZipPath(uuid);
Hernoemd naar `pad` op alle plekken waar van toepassing in opvolgende commit

2022-09-26 13:30 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +        String zaakId = ZAAK_ONTKOPPELD;
Opgelost in opvolgende commit. Aangezien het geval dat de `ZaakInformatieObject`-koppeling niet bestaat niet kan voorkomen heb ik de `if`-statement hieronder aangepast naar een assertion boven het toewijzen van de zaakId. Daardoor kan de zaakId ook final worden gemaakt.

2022-09-26 13:31 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +        if(zaakInformatieObjectenList.size() > 0) {
Ga ik op letten, opgelost in opvolgende commit. Is er trouwens een linter die we intern gebruiken voor dit soort code style dingetjes?

2022-09-26 13:31 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +    private void addInformatieObjectToSummary(final String pad, Map<String, Map<String, List<String>>> samenvatting) {
Ga ik in het vervolg op letten. Deze en andere velden en methoden zo veel mogelijk vertaald naar het Nederlands, met uitzondering van standaard-werkwoorden zoals `add`, `get`, etc.

2022-09-26 13:33 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +    private void addInformatieObjectToSummary(final String pad, Map<String, Map<String, List<String>>> samenvatting) {
Opgelost in opvolgende commit

2022-09-26 13:34 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +    private void addSamenvattingToZip(Map<String, Map<String, List<String>>> samenvatting, ZipOutputStream zipOutputStream) {
Opgelost in opvolgende commit

2022-09-26 13:36 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +            final Map<String, List<String>> zaakRichtingen = samenvatting.get(zaak);
Omdat de `get` op de map dan niet twee keer aangeroepen hoeft te worden

2022-09-26 13:39 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +            for(String richting : zaakRichtingen.keySet()) {
Opgelost in opvolgende commit.

2022-09-26 13:39 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +                for(String bestand : zaakRichtingen.get(richting)) {
Opgelost in opvolgende commit.

2022-09-26 13:39 UTC, jeroen-dekker commented on src/main/java/net/atos/zac/app/informatieobjecten/EnkelvoudigInformatieObjectDownloadService.java
> +        final byte[] samenvattingInhoud = stringBuilder.toString().getBytes();
Opgelost in opvolgende commit.

2022-09-27 07:07 UTC, marcoatos approved these changes

2022-09-27 07:07 UTC, merged