zaakafhandelcomponent-1801 - Beheerinstelling voor mailtemplates
NL-AMS-LOCGOV/zaakafhandelcomponent pull request #1816
Opened 2022-11-01 18:00 UTC by marcoatos

zaakafhandelcomponent-1801 - Beheerinstelling voor mailtemplates

2022-11-02 07:02 UTC, andyverberne requested changes
Paar dingen even bespreken.

2022-11-02 07:02 UTC, andyverberne commented on src/main/java/net/atos/zac/app/admin/MailtemplateRESTService.java
> +    public RESTMailtemplate readMailtemplate(@PathParam("id") final long id) {
Deze methode kan dus niet geberuikt worden door een zaakbehandelaar om een mailtemplate op te halen. Dat is prima. Daar moet dan nog een andere service en RESTService voor komen. Maar noem deze service dan ook MailtemplateBeheerRESTService (ook aan de typescript kant)

2022-11-02 13:15 UTC, marcoatos commented on src/main/app/src/app/admin/model/mailtemplate.ts
> +    mailTemplateEnum: string;
Gebeurt in volgende subtask

2022-11-02 13:15 UTC, marcoatos commented on src/main/java/net/atos/zac/app/admin/model/RESTMailtemplate.java
> +    public String mailTemplateEnum;
Gebeurt in volgende subtask

2022-11-02 13:16 UTC, marcoatos commented on src/main/app/src/app/admin/mailtemplate.service.ts
> +export class MailtemplateService {
Er komt nog een gebruikersservice om templates op te halen op het moment dat de mail verzonden moet gaan worden, Ik zal deze service wel hernoemen naar beheer service

2022-11-04 09:50 UTC, marcoatos commented on src/main/app/src/app/admin/mailtemplates/mailtemplate.component.html
> +                                        (onSave)="editMailtemplate($event, 'mailTemplateNaam')"></zac-edit-input>
Gaat aangepast worden in de volgende subtask

2022-11-04 09:56 UTC, merged