zaakafhandelcomponent-2249 10C3.1.6 Zoeken BAG-objecten
NL-AMS-LOCGOV/zaakafhandelcomponent pull request #2413
Opened 2023-03-23 14:48 UTC by ronniekoopmans-atos

zaakafhandelcomponent-2249 10C3.1.6 Zoeken BAG-objecten - initial commit

2023-03-24 08:58 UTC, andyverberne requested changes

2023-03-24 08:58 UTC, andyverberne commented on src/main/app/src/app/bag/bag.service.ts
> +
lege regel verwijderen

2023-03-24 08:58 UTC, andyverberne commented on src/main/java/net/atos/client/bag/util/IndicatieEnumAdapter.java
> +    public String adaptToJson(final Indicatie indicatie) throws Exception {
throws Exception mag er af

2023-03-24 08:58 UTC, andyverberne commented on src/main/java/net/atos/client/bag/util/StatusPandEnumAdapter.java
> +    public String adaptToJson(final StatusPand statusPand) throws Exception {
throws Exception mag er af.

2023-03-24 08:58 UTC, andyverberne commented on src/main/java/net/atos/client/bag/util/StatusWoonplaatsEnumAdapter.java
> +    public String adaptToJson(final StatusWoonplaats statusWoonplaats) throws Exception {
throws Exception mag er af.

2023-03-24 08:58 UTC, andyverberne commented on src/main/java/net/atos/zac/app/bag/converter/RESTPandConverter.java
> +        if (panden != null) {
In de andere classes check je juist eerst op xxx == null

2023-03-24 08:58 UTC, andyverberne commented on src/main/java/net/atos/zac/app/bag/model/RESTNummeraanduiding.java
> +    public RESTNummeraanduiding() {
Ddeze is niet nodig.

2023-03-24 08:58 UTC, andyverberne commented on src/main/java/net/atos/zac/app/bag/model/RESTOpenbareRuimte.java
> +    public RESTOpenbareRuimte() {
Ddeze is niet nodig.

2023-03-24 08:58 UTC, andyverberne commented on src/main/java/net/atos/zac/app/bag/model/RESTPand.java
> +    public RESTPand() {
Ddeze is niet nodig.

2023-03-24 08:58 UTC, andyverberne commented on src/main/java/net/atos/zac/app/bag/model/RESTWoonplaats.java
> +    public RESTWoonplaats() {
Ddeze is niet nodig.

2023-03-24 08:58 UTC, andyverberne commented on src/main/java/net/atos/zac/app/bag/BAGRESTService.java
> +                    .map(adres -> adresConverter.convertToREST(adres))
.map(adresConverter::convertToREST)

2023-03-27 06:28 UTC, ronniekoopmans-atos commented on src/main/java/net/atos/zac/app/audit/converter/zaken/AuditZaakobjectWijzigingConverter.java
> +        return contains(path, "/") ? substringAfterLast(path, "/") : path;
Is geen uuid, dus laat het maar zo

2023-03-27 06:34 UTC, merged