zaakafhandelcomponent-158 6B.3.1 Overdragen zaak door behandelaar aan…
NL-AMS-LOCGOV/zaakafhandelcomponent pull request #245
Opened 2022-01-12 08:37 UTC by hansmarks

… een andere behandelaar/groep

2022-01-14 15:07 UTC, andyverberne requested changes
Ik weet niet of wij iets doen met TSLINT? Bij in Intellij krijg ik rode streepjes en ook suggesties om het te fixen

2022-01-14 15:07 UTC, andyverberne commented on src/main/app/src/app/shared/directives/outside-click.directive.ts
> +        let included: boolean = this.inclusions.some(value => clickTarget.classList.contains(value));
TSLINT suggereert om 'let' te veranderen in 'const'

2022-01-14 15:07 UTC, andyverberne commented on src/main/app/src/app/shared/directives/outside-click.directive.ts
> +        return element == clickTarget || element.contains(clickTarget) || included;
TSLINT suggereert om van '==' '===' te maken

2022-01-14 15:07 UTC, andyverberne commented on src/main/app/src/app/shared/directives/outside-click.directive.ts
>      private static isOrContainsClickTarget(element: HTMLElement, clickTarget: HTMLElement) {
TSLINT suggereert dat deze methode meer boven in de clas moet

2022-01-17 09:29 UTC, hansmarks commented
Opgelost, hoewel ik niets heb aangepast in dat bestand.

2022-01-17 09:34 UTC, merged