zaakafhandelcomponent-536 - Wissen zoekparameters Mijn Zaken
NL-AMS-LOCGOV/zaakafhandelcomponent pull request #549
Opened 2022-02-23 14:26 UTC by edwinlambregts-atos

#536

2022-02-23 14:31 UTC, hansmarks requested changes

2022-02-24 07:28 UTC, edwinlambregts-atos commented on src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
> +            zaaktype: ''
Zaaktype is juist degene die leeg gemaakt moet worden. Ik heb dit op dezelfde manier gedaan als bij de Zaken Werkvoorraad en Afgehandelde zaken.
Het is ook mogelijk om bijv. dit te doen: this.dataSource.zoekParameters.zaaktype = '';

2022-02-24 07:55 UTC, hansmarks commented on src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
> +            zaaktype: ''
Als je er neerzet this.dataSource.zoekParameters = {} dan IS zaaktype leeg. Alle andere parameters ook trouwen maar dat doe je nu ook. Als je alleen zaaktype leeg zou willen maken dan kun je remove this.dataSource.zoekParameters gebruiken. En bovendien je maakt zaaktype nu niet leeg je maakt er een lege string van.

2022-02-28 09:13 UTC, edwinlambregts-atos commented on src/main/app/src/app/zaken/zaken-mijn/zaken-mijn.component.ts
> +            zaaktype: ''
Zaaktype word nu leeggegooid met
delete this.dataSource.zoekParameters.zaaktype;

Er zitten bindings op en als ik .zaaktype weglaat komen er allerlei errors in de console.

2022-02-28 13:44 UTC, merged