Zaakafhandelcomponent-174 -> Eerste opzet mailfunctionaliteit
NL-AMS-LOCGOV/zaakafhandelcomponent pull request #562
Opened 2022-03-02 10:37 UTC by marcoatos

Zaakafhandelcomponent-174 -> Eerste opzet mailfunctionaliteit

2022-03-03 07:16 UTC, andyverberne requested changes

2022-03-03 07:16 UTC, andyverberne commented on src/main/java/net/atos/zac/mail/MailService.java
> +        final MailjetRequest request = new MailjetRequest(Emailv31.resource)
Maak een EMail java object aan met eventueel JSON-B annotaties om de mail te representeren

2022-03-03 07:16 UTC, andyverberne commented on src/main/app/src/app/mail/mail-create/mail-create.component.ts
> +                    const file = new File([mailObject.body as BlobPart], mailObject.onderwerp + '.txt');
Verplaats de logica voor het aanmakenb van de file naar dew backend. Naar de MailService class.

2022-03-04 10:24 UTC, marcoatos commented on src/main/java/net/atos/zac/mail/MailService.java
> +        final MailjetRequest request = new MailjetRequest(Emailv31.resource)
Opgelost

2022-03-04 10:24 UTC, marcoatos commented on src/main/app/src/app/mail/mail-create/mail-create.component.ts
> +                    const file = new File([mailObject.body as BlobPart], mailObject.onderwerp + '.txt');
Opgelost

2022-03-07 07:36 UTC, andyverberne requested changes

2022-03-07 07:36 UTC, andyverberne commented on src/main/java/net/atos/zac/mail/MailService.java
> +        return restInformatieobjecttypeConverter.convert(zaaktype.getInformatieobjecttypen());
Het is niet nodig om de Informatieobjecttypen te converteren naar een REST object. Hier gewoon een call doen naar ztcClientService::readInformatieobjecttype en Informatieobjecttype gebruiken. Kijk maar wat er gebeurt in de converter.

2022-03-07 07:36 UTC, andyverberne commented on src/main/java/net/atos/zac/mail/MailService.java
> +        final RESTInformatieobjecttype eMailObjectType =
Hier niet het REST object gebruiken maar Informatieobjecttype gebruiken (zie ook commentaar verderop_)

2022-03-07 08:42 UTC, merged