Eerste opzet zaaklocatie toevoegen
NL-AMS-LOCGOV/zaakafhandelcomponent pull request #659
Opened 2022-03-29 05:51 UTC by bartlukens-atos

2022-03-29 10:12 UTC, andyverberne requested changes

2022-03-29 10:12 UTC, andyverberne commented on src/main/java/net/atos/client/zgw/zrc/util/GeometryJsonbDeserializer.java
> +            default -> throw new IllegalStateException("Unexpected value: " + geometryType);
Aangezien GeometrytType een enum is is deze default niet nodif. De compiler checkt wanneer er een waarde bij komt.

2022-03-29 10:12 UTC, andyverberne commented on src/main/java/net/atos/client/zgw/zrc/util/GeometryJsonbDeserializer.java
> +                return JSONB.fromJson(jsonObject.toString(), Point.class);
Zet de return voor de switch (switch expression). Die curly braces zijn dan ook niet meer nodig
Dus:

return switch(geometryType) {
     case POINT -> JSONB.from......;();
     case POLYGON -> JSONB.from....();

2022-03-29 10:12 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zaken/converter/RESTGeometryConverter.java
> +            default -> throw new IllegalStateException("Unexpected value: " + geometry.getType());
default is niet nodig

2022-03-29 10:12 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zaken/converter/RESTGeometryConverter.java
> +                    .collect(Collectors.toList());
Maak hier een aparte method van. En zo ook van de volgende

2022-03-29 10:12 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zaken/converter/RESTGeometryConverter.java
> +        switch (GeometryType.fromValue(restGeometry.type)) {
geometry = switch() ...

2022-03-29 10:12 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zaken/converter/RESTGeometryConverter.java
> +                        .map(coordinates -> new Point2D(new BigDecimal(coordinates.x), new BigDecimal(coordinates.y)))
Je kunt een constructor toeoegen aan Point2D die dan de BigDecimal maakt.

2022-03-29 10:12 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zaken/converter/RESTGeometryConverter.java
> +                        .collect(Collectors.toList()))
Volgens mij is hier nu een toList() voor. Dan heb je geen collect nodig

2022-03-29 10:12 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zaken/converter/RESTGeometryConverter.java
> +        for (final RESTGeometry geometry : restGeometry.geometrycollection) {
Dit kan natuurlijk ook met een stream :-)

2022-03-29 10:12 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zaken/model/RESTCoordinates.java
> +    public RESTCoordinates(final double x, final double y) {
Ik dacht dat je geen x en y wou gebruiken maar longitue en lattitude?

2022-04-01 12:00 UTC, bartlukens-atos commented on src/main/app/src/app/zaken/model/geometry.ts
> +    constructor(type: 'Point' | 'Polygon' | 'GeometryCollection') {
Je kunt in typescript niet je constructors overloaden, omdat het op de achtergrond naar javascript vertaald wordt is het dan niet duidelijk welke wordt aangeroepen.

2022-04-01 12:03 UTC, bartlukens-atos commented on src/main/app/src/app/zaken/model/geometry.ts
> +    constructor(x: number, y: number) {
Vanuit de map kreeg ik ook x en y terug, dus heb het zo gelaten

2022-04-04 11:26 UTC, merged