zaakafhandelcomponent-818 Zoek zaken - Realiseren SOLR index
NL-AMS-LOCGOV/zaakafhandelcomponent pull request #851
Opened 2022-04-29 07:26 UTC by ronniekoopmans-atos

fixes #818

2022-05-05 06:53 UTC, andyverberne requested changes

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zoeken/converter/RESTZoekZaakParametersConverter.java
> +        final ZaakZoekParameters zoekZaakParameters = new ZaakZoekParameters();
zoekZaakParameters hernoemen naar zaakZoekParameters

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zoeken/converter/RESTZoekZaakResultaatConverter.java
>  public class RESTZoekZaakResultaatConverter {
hernoemen naar RESTZaakZoekResultaatConverter

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zoeken/model/RESTZaakZoekItem.java
> +    public String zaaktypeNaam;
hernoemen naar zaaktypeOmschrijving

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zoeken/converter/RESTZoekZaakResultaatConverter.java
> +        return restZoekItem;
restZoekItem.resultaatNaam en restZoekItem.locatie worden niet gevuld

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zoeken/ZoekenRESTService.java
> +    public RESTResult<RESTZaakZoekItem> zoekZaken(@BeanParam final RESTZoekZaakParameters zoekZaakParameters) {
zoekZaakParameters hernoemen naar zaakZoekParameters

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/app/zoeken/ZoekenRESTService.java
> +        return zoekZaakResultaatConverter.convert(zoekResultaat);
zoekZaakResultaatConverter hernoemen naat zaakZoekResultaatConverter

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String type;
type moet een enum zijn

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String communicatiekanaal;
hernoemen naar communicatiekanaalNaam (geld ook voor @Field naam)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String groepID;
hernoemen naar groepId

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private boolean afgehandeld;
hernoemen naar isAfgehandeld (geld ook voor @Field naam)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String behandelaarGebruikersnaam;
hernoemen naar behandelaarId (geld ook voor @Field naam)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String duurVerlenging;
hernoemen naar verlengingDuur (geld ook voor @Field naam)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String redenVerlenging;
hernoemen naar verlengingReden (geld ook voor @Field naam)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private boolean IndicatieVerlenging;
hernoemen naar verlengingIndicatie (geld ook voor @Field naam)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String redenOpschorting;
hernoemen naar opschortingReden (geld ook voor @Field naam)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String statusNaam;
hernoemen naar statustypeOmschrijving (geld ook voor @Field naam)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String resultaatNaam;
hernoemen naar resultaattypeOmschrijving (geld ook voor @Field naam)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String statusToekenningsdatum;
hernoemen naar statusDatumStatusGezet

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/converter/ZaakZoekItemConverter.java
> +    private String getVolledigeNaam(final User user) {
Het bepalen van de volledige naam is logica die bij het User object moet zitten.

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/converter/ZaakZoekItemConverter.java
> +    private User getBehandelaar(final Zaak zaak) {
hernoemen naar findBehandelaar (hij kan immers null retourneren)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/converter/ZaakZoekItemConverter.java
> +    private Group getGroep(final Zaak zaak) {
hernoemen naar findGroep (hij kan immers null retourneren)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/converter/ZaakZoekItemConverter.java
> +    private CommunicatieKanaal getCommunicatieKanaal(final Zaak zaak){
hernoemen naar findCommunicatiekanaal (hij kan immers null retourneren)

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/model/ZaakZoekItem.java
> +    private String initiatorIdentificatie;
Opsplitsen in 2 velden: initiatorBSN em initiatorVestigingsnummer

2022-05-05 06:53 UTC, andyverberne commented on src/main/java/net/atos/zac/zoeken/ZoekenService.java
> +    public ZoekResultaat<ZaakZoekItem> zoekZaak(final ZaakZoekParameters zoekZaakParameters) {
zoekZaakParameters hernoemen naar zaakZoekParameters

2022-05-09 11:27 UTC, ronniekoopmans-atos reviewed
review verwerkt

2022-05-09 11:28 UTC, merged